app/Controllers/AcknowledgementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Calendar.Data;
using Calendar.Models;
using Calendar.Helpers;

namespace Calendar.Controllers
{
    public class AcknowledgementsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AcknowledgementsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Acknowledgements
        public async Task<IActionResult> Index(int? eventid)
        {
            if (eventid == null)
                return View(await _context.Acknowledgement.ToListAsync());
            else
            {
                return View(await _context.Acknowledgement.Where(m => m.EventID == eventid).ToListAsync());
            }
        }

        // GET: Acknowledgements
        public async Task<IActionResult> IndexPartial(int eventid)
        {
            return PartialView("AckPartial", await _context.Acknowledgement.Where(m => m.EventID == eventid).ToListAsync());
        }

        // GET: Acknowledgements/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var acknowledgement = await _context.Acknowledgement.SingleOrDefaultAsync(m => m.ID == id);
            if (acknowledgement == null)
            {
                return NotFound();
            }

            return View(acknowledgement);
        }

        // GET: Acknowledgements/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Acknowledgements/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,AckMessage,CreatedBy,CreatedByDisplayName,CreatedDate,EventID,Team,UpdatedBy,UpdatedByDisplayName,UpdatedDate")] Acknowledgement acknowledgement, string redir, string ajax)
        {
            if (!User.Identity.IsAuthenticated)
                return NotFound();

            if (ModelState.IsValid)
            {
                /* Audit Fields */
                var username = "anonymous";
                var u = User.Claims.Where(m => m.Type == "username");
                if (u.Count() == 1) { username = u.First().Value; }
                var displayname = "anonymous";
                var d = User.Claims.Where(m => m.Type == "displayName");
                if (d.Count() == 1) { displayname = d.First().Value; }
                acknowledgement.CreatedDate = DateTime.Now;
                acknowledgement.CreatedBy = username;
                acknowledgement.CreatedByDisplayName = displayname;
                acknowledgement.UpdatedDate = acknowledgement.CreatedDate;
                acknowledgement.UpdatedBy = username;
                acknowledgement.UpdatedByDisplayName = displayname;


                _context.Add(acknowledgement);
                await _context.SaveChangesAsync();


                if (ajax == "true")
                    return new EmptyResult();
                else if (redir == "")
                    return RedirectToAction("Index");
                else
                {
                    RedirectToActionResult redirectResult = new RedirectToActionResult("Details", "Events", new { @id = acknowledgement.EventID, @redir = redir });
                    return redirectResult;
                }

            }
            return View(acknowledgement);
        }

        // GET: Acknowledgements/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!User.Identity.IsAuthenticated)
                return NotFound();

            if (id == null)
            {
                return NotFound();
            }

            var acknowledgement = await _context.Acknowledgement.SingleOrDefaultAsync(m => m.ID == id);
            if (acknowledgement == null)
            {
                return NotFound();
            }
            return View(acknowledgement);
        }

        // POST: Acknowledgements/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,AckMessage,CreatedBy,CreatedByDisplayName,CreatedDate,EventID,Team,UpdatedBy,UpdatedByDisplayName,UpdatedDate")] Acknowledgement acknowledgement)
        {
            if (!User.Identity.IsAuthenticated)
                    return NotFound();

            if (id != acknowledgement.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(acknowledgement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AcknowledgementExists(acknowledgement.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(acknowledgement);
        }

        // GET: Acknowledgements/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!User.Identity.IsAuthenticated)
                return NotFound();

            if (id == null)
            {
                return NotFound();
            }

            var acknowledgement = await _context.Acknowledgement.SingleOrDefaultAsync(m => m.ID == id);
            if (acknowledgement == null)
            {
                return NotFound();
            }

            return View(acknowledgement);
        }

        // POST: Acknowledgements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, string ajax)
        {
            if (!User.Identity.IsAuthenticated)
                return NotFound();

            var acknowledgement = await _context.Acknowledgement.SingleOrDefaultAsync(m => m.ID == id);
            _context.Acknowledgement.Remove(acknowledgement);
            await _context.SaveChangesAsync();
            if (ajax == "true")
                return new EmptyResult();
            else
                return RedirectToAction("Index");
        }

        private bool AcknowledgementExists(int id)
        {
            return _context.Acknowledgement.Any(e => e.ID == id);
        }
    }
}

app/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Calendar.Data;
using Calendar.Models;
using Calendar.Models.CalendarViewModels;
using Calendar.Helpers;

namespace Calendar.Controllers
{
    public class EventsController : Controller
    {
        const int DAYSINAWEEK = 7;
        private readonly ApplicationDbContext _context;


        public EventsController(ApplicationDbContext context)
        {
            _context = context;    
        }


        // GET: Events
        //startdate_desc, startdate_asce, creation_desc, creation_asce
        public async Task<IActionResult> Index(string sort, string eventid, string subject, string searchrange, string searchday, string host, string project, string team, string refid, string searchdatefrom, string searchdateto, int? page, int? pgsize)
        {
            ViewBag.SortParm = String.IsNullOrEmpty(sort) ? "" : sort;
            ViewBag.SubjectParm = String.IsNullOrEmpty(subject) ? "" : subject;
            ViewBag.HostParm = String.IsNullOrEmpty(host) ? "" : host;
            ViewBag.ProjParm = String.IsNullOrEmpty(project) ? "" : project;
            ViewBag.TeamParm = String.IsNullOrEmpty(team) ? "" : team;
            ViewBag.RefParm = String.IsNullOrEmpty(refid) ? "" : refid;
            ViewBag.RangeParm = searchrange;
            ViewBag.DayParm = searchday;
            ViewBag.EventParm = String.IsNullOrEmpty(eventid) ? "" : eventid;
            ViewBag.FromParm = String.IsNullOrEmpty(searchdatefrom) ? "" : searchdatefrom;
            ViewBag.ToParm = String.IsNullOrEmpty(searchdateto) ? "" : searchdateto;
            
            if (String.IsNullOrEmpty(eventid) && String.IsNullOrEmpty(subject) 
                && String.IsNullOrEmpty(host) && String.IsNullOrEmpty(project) 
                && String.IsNullOrEmpty(team) && String.IsNullOrEmpty(refid) 
                && (String.IsNullOrEmpty(searchday) || searchday.Equals("ND")))
            {
                ViewBag.SearchOn = "";
            } else
            {
                ViewBag.SearchOn = "in";
            }

            var events = from e in _context.Event
                           select e;

            int n_eventid;          
            if (!String.IsNullOrEmpty(eventid) && Int32.TryParse(eventid, out n_eventid))
            {
                events = events.Where(e => e.ID.Equals(n_eventid));
            }

            if (!String.IsNullOrEmpty(subject))
            {
                events = events.Where(e => e.Subject.Contains(subject));
            }
            if (!String.IsNullOrEmpty(host))
            {
                events = events.Where(e => e.AffectedHosts.Contains(host));
            }
            if (!String.IsNullOrEmpty(project))
            {
                events = events.Where(e => e.AffectedProjects.Contains(project));
            }
            if (!String.IsNullOrEmpty(team))
            {
                events = events.Where(e => e.AffectedTeams.Contains(team));
            }
            if (!String.IsNullOrEmpty(refid))
            {
                events = events.Where(e => e.Reference.Contains(refid));
            }

            DateTime datetimefrom;
            DateTime datetimeto;

            if (!String.IsNullOrEmpty(searchdatefrom) || !String.IsNullOrEmpty(searchdateto))
            {

                if (searchday.Equals("SD"))
                {
                    if (!String.IsNullOrEmpty(searchdatefrom) && DateTime.TryParse(searchdatefrom, out datetimefrom))
                    {
                        events = events.Where(e => e.StartDateTime >= datetimefrom);
                    }
                    if (!String.IsNullOrEmpty(searchdateto) && DateTime.TryParse(searchdateto, out datetimeto))
                    {
                        events = events.Where(e => e.EndDateTime <= datetimeto);
                    }
                }
                else if(searchday.Equals("CD"))
                {
                    if (!String.IsNullOrEmpty(searchdatefrom) && DateTime.TryParse(searchdatefrom, out datetimefrom))
                    {
                        events = events.Where(e => e.CreatedDate >= datetimefrom);
                    }
                    if (!String.IsNullOrEmpty(searchdateto) && DateTime.TryParse(searchdateto, out datetimeto))
                    {
                        events = events.Where(e => e.CreatedDate <= datetimeto);
                    }
                }
                else
                {
                    if (!String.IsNullOrEmpty(searchdatefrom) && DateTime.TryParse(searchdatefrom, out datetimefrom))
                    {
                        events = events.Where(e => e.UpdatedDate >= datetimefrom);
                    }
                    if (!String.IsNullOrEmpty(searchdateto) && DateTime.TryParse(searchdateto, out datetimeto))
                    {
                        events = events.Where(e => e.UpdatedDate <= datetimeto);
                    }
                }
            }
            else
            {                
                switch (searchrange)
                {
                    case "S1":
                        events = events.Where(e => e.StartDateTime.Date >= DateTime.Now.Date && e.StartDateTime.Date <= (DateTime.Now.AddDays(1).Date));
                        break;
                    case "S2":
                        events = events.Where(e => e.StartDateTime.Date >= DateTime.Now.Date && e.StartDateTime.Date <= (DateTime.Now.AddDays(7).Date));
                        break;
                    case "S3":
                        events = events.Where(e => e.StartDateTime.Date >= DateTime.Now.Date && e.StartDateTime.Date <= (DateTime.Now.AddDays(30).Date));
                        break;
                    case "S4":
                        events = events.Where(e => e.StartDateTime.Date >= DateTime.Now.Date && e.StartDateTime.Date <= (DateTime.Now.AddDays(90).Date));
                        break;
                    case "C1":
                        events = events.Where(e => e.CreatedDate.Date >= DateTime.Now.Date && e.CreatedDate.Date <= (DateTime.Now.AddDays(1).Date));
                        break;
                    case "C2":
                        events = events.Where(e => e.CreatedDate.Date >= (DateTime.Now.AddDays(-7).Date) && e.CreatedDate.Date <= DateTime.Now.Date);
                        break;
                    case "C3":
                        events = events.Where(e => e.CreatedDate.Date >= (DateTime.Now.AddDays(-30).Date) && e.CreatedDate.Date <= DateTime.Now.Date);
                        break;
                    case "C4":
                        events = events.Where(e => e.CreatedDate.Date >= (DateTime.Now.AddDays(-90).Date) && e.CreatedDate.Date <= DateTime.Now.Date);
                        break;
                    case "U1":
                        events = events.Where(e => e.UpdatedDate.Date >= DateTime.Now.Date && e.UpdatedDate.Date <= (DateTime.Now.AddDays(1).Date));
                        break;
                    case "U2":
                        events = events.Where(e => e.UpdatedDate.Date >= (DateTime.Now.AddDays(-7).Date) && e.UpdatedDate.Date <= DateTime.Now.Date);
                        break;
                    case "U3":
                        events = events.Where(e => e.UpdatedDate.Date >= (DateTime.Now.AddDays(-30).Date) && e.UpdatedDate.Date <= DateTime.Now.Date);
                        break;
                    case "U4":
                        events = events.Where(e => e.UpdatedDate.Date >= (DateTime.Now.AddDays(-90).Date) && e.UpdatedDate.Date <= DateTime.Now.Date);
                        break;
                    default:
                        break;
                }
            }

            switch (sort)
            {
                case "cd_a":
                    events = events.OrderBy(e => e.CreatedDate);
                    break;
                case "cd_d":
                    events = events.OrderByDescending(e => e.CreatedDate);
                    break;
                case "ud_a":
                    events = events.OrderBy(e => e.UpdatedDate);
                    break;
                case "ud_d":
                    events = events.OrderByDescending(e => e.UpdatedDate);
                    break;
                case "sd_a":
                    events = events.OrderBy(e => e.StartDateTime);
                    break;
                default:   // sd_d
                    events = events.OrderByDescending(e => e.StartDateTime);
                    break;
            }
            
            var viewModel = new EventIndexData();
            viewModel.Events = events
                  .Include(e => e.Acknowledgements)
                  .AsNoTracking();
            
            return View(new PaginatedEventIndex(viewModel, page ?? 1, pgsize ?? 30));

            //return View(await PaginatedList<Event>.CreateAsync(events.AsNoTracking(), page ?? 1, pgsize ?? 30));

            //return View(await events.AsNoTracking().ToListAsync());
            //return View(await _context.Event.OrderByDescending(m => m.StartDateTime).ToListAsync());
        }


        // GET: Events/Calendar
        public async Task<IActionResult> Calendar(int? year, int? month, int? reviewEventId, int? reviewDirection, string filterProject, string filterTeam)
        {
            DateTime now = System.DateTime.Now;
            DateTime ViewDate;

            if (year == null)
            {
                year = now.Year;
                month = now.Month;
            } else if (month == null)
            {
                month = now.Month;                
            }

            try
            {
                ViewDate = new DateTime((int)year, (int)month, 1);
            }
            catch (ArgumentOutOfRangeException)

app/Views/Shared/AckPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@model IEnumerable<Calendar.Models.Acknowledgement>

@{
    ViewData["Title"] = "Team Acknowledgements";

    string username = (User.Identity.IsAuthenticated) ? User.Claims.Where(m => m.Type == "username").SingleOrDefault().Value : "";
}

<div classx="xbg-info">
<table class="table table-condensed xtable-bordered" id="idTeamAckTable">
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="idTeamAckRow-@item.ID" class="small">
                <td style="width:50%;" >
                    @{
                        var displayname = item.UpdatedByDisplayName.Substring(0, item.UpdatedByDisplayName.IndexOf(','));
                        var date = item.UpdatedDate.ToString("MMM dd, yyyy");
                        var time = item.UpdatedDate.ToString("h:mmtt").ToLower();
                    }                    
                    <span id="idTeamAckTeam-@item.Team">@Html.DisplayFor(modelItem => item.Team)</span> <span class="text-primary"><strong>@displayname</strong></span>
                    <p class="text-muted p-inline">said</p> 
                    @if (item.AckMessage == null)
                    {
                        <p class="text-muted p-inline">Nothing</p>
                    }
                    else
                    {
                    <p class="text-primary p-inline">@Html.DisplayFor(modelItem => item.AckMessage)</p>
                    }
                    <br /><p class="text-muted p-inline">@date at @time</p>
                </td>
                <td>
                    <form class="formTeamAckRow @(User.Identity.IsAuthenticated && username == item.UpdatedBy? "":"hidden")" asp-controller="Acknowledgements" asp-action="Delete" asp-route-id="@item.ID" method="post">
                        <div class="form-actions no-color">
                            <input type="hidden" name="ackid" value="@item.ID" />
                            <input type="hidden" name="team" value="@item.Team" />
                            <input type="hidden" name="ajax" value="true" />
                            <button type="submit" value="Delete" class="btn btn-default btn-xs hidden border-none" data-toggle="tooltip" data-placement="top" data-htmlx="true" title="Remove this">
                                <span class="text-muted glyphicon glyphicon-remove"></span>
                            </button>
                        </div>
                    </form>
                </td>
            </tr>            
        }
    </tbody>
</table>
</div> 

<script type="text/javascript">
    $(document).ready(function () {
      /* bind the form submit action - delete */
      $('.formTeamAckRow').on('submit', function (e) {
        var ackid = $(this).find('input[name="ackid"]').val();
        var team = $(this).find('input[name="team"]').val();
          
        e.preventDefault();
        $.ajax({
            type: $(this).attr('method'),
            url: $(this).attr('action'),
            data: $(this).serialize(),
            success: function (data) {
                $('#idTeamAckRow-' + ackid).remove();

                if ($('#idTeamAckTeam-' + team).length == 0) {
                    $('#idAffectedTeam-' + team).removeClass('acknowledged');
                    $('#idAffectedTeam-' + team).addClass('not-acknowledged');
                }                
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert('Status: ' + textStatus + ', Error: ' + errorThrown);
            }
        });        
      });

      /* bind the hover table row. show/hide the delete button*/
      $('#idTeamAckTable tr').hover(function () {          
          $(":button", this).removeClass('hidden');
      }, function () {          
          $(":button", this).addClass('hidden');
      });
  });

</script>

app/Views/Shared/AttachPartial.cshtml
@model IEnumerable<Calendar.Models.Attachment>

@{
    ViewData["Title"] = "Team Attachments";

    string username = (User.Identity.IsAuthenticated) ? User.Claims.Where(m => m.Type == "username").SingleOrDefault().Value : "";
}

@functions{
    public string getFileClass(string targetFile)
    {
        string fileClass;
        string fileExt = targetFile.Substring(targetFile.LastIndexOf(".") + 1);
        switch (fileExt)
        {
            case "doc":
            case "docx":
                fileClass = "fa-lg fa fa-file-word-o text-primary";
                break;
            case "xls":
            case "xlsx":
            case "xlsm":
                fileClass = "fa-lg fa fa-file-excel-o text-success";
                break;
            case "ppt":
            case "pptx":
                fileClass = "fa-lg fa fa-file-powerpoint-o text-danger";
                break;
            case "txt":
            case "log":
                fileClass = "fa-lg fa fa-file-text-o text-info";
                break;
            case "zip":
            case "7z":
            case "rar":
                fileClass = "fa-lg fa fa-file-zip-o text-muted";
                break;
            case "jpg":
                fileClass = "fa-lg fa fa-file-photo-o text-danger";
                break;
            case "png":
                fileClass = "fa-lg fa fa-file-photo-o text-primary";
                break;
            case "gif":
                fileClass = "fa-lg fa fa-file-photo-o text-muted";
                break;
            case "pdf":
                fileClass = "fa-lg fa fa-file-pdf-o text-danger";
                break;
            case "msg":
                fileClass = "fa-lg fa fa-envelope-o text-warning";
                break;
            default:
                fileClass = "glyphicon glyphicon-paperclip";
                break;
        }
        return fileClass;
    }    
}

<div classx="xbg-info">
    <table class="table table-condensed xtable-bordered" id="idAttachTable">
        <tbody>
                <tr class="small">
                    <td >
                    @foreach (var item in Model)
                    {
                        string title = "Created by: <br>" + @item.CreatedByDisplayName + "<br> Creation Date: <br>" + @item.CreatedDate;
                        <span id="idAttachRow-@item.ID"  style="display: inline-block;" onmouseover="showbutton(this); " onmouseout="hidebutton(this); ">
                            <i id="idAttachRow-@item.ID" class="@getFileClass(@item.FileName)"></i>
                            <a id="idAttachRow-@item.ID"
                               href="@Context.Request.PathBase/uploads/@item.EventID/@item.ID/@item.FileName"
                               target="_blank"
                               data-toggle="tooltip"
                               data-html="true"                              
                               title="Uploaded by @Html.DisplayFor(modelItem => item.CreatedByDisplayName) at @Html.DisplayFor(modelItem => item.CreatedDate)">
                                @Html.DisplayFor(modelItem => item.FileName)
                            </a>
                            <form id="idAttachRow-@item.ID" style="display:inline;" class="formAttachRow @(User.Identity.IsAuthenticated? "":"hidden")" asp-controller="Attachments" asp-action="Delete" asp-route-id="@item.ID" method="post">
                                <input type="hidden" name="attachid" value="@item.ID" />
                                <button id="idAttachBtn-@item.ID" type="submit" value="Delete" class="btn btn-default hidden btn-xs border-none" data-toggle="tooltip" data-placement="top" data-htmlx="true" title="Remove this">
                                    <span class="text-muted glyphicon glyphicon-remove"></span>
                                </button>
                                <button id="idAttachSpace-@item.ID" type="submit" value="Delete" class="btn btn-default btn-xs border-none" data-toggle="tooltip" data-placement="top" data-htmlx="true" title="Remove this">
                                    <span class="text-muted glyphicon glyphicon-remove invisbleCrossbtn"></span>
                                </button>
                            </form>
                        </span>
                    }
                    </td>
                </tr>
        </tbody>
    </table>
</div>


<script type="text/javascript">

    $(document).ready(function () {

      $('.formAttachRow').on('submit', function (e) {
          var attachid = $(this).find('input[name="attachid"]').val();

        e.preventDefault();
        $.ajax({
            type: $(this).attr('method'),
            url: $(this).attr('action'),
            data: $(this).serialize(),
            success: function (data) {
                $('a').remove('#idAttachRow-' + attachid);
                $('i').remove('#idAttachRow-' + attachid);
                $('form').remove('#idAttachRow-' + attachid);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert('Status: ' + textStatus + ', Error: ' + errorThrown);
            }
        });
      });

  });

    function showbutton(obj) {
        var linkid = obj.id;
        var btnid = linkid.replace("idAttachRow-", "");
        $("#idAttachBtn-" + btnid).removeClass('hidden');
        $("#idAttachSpace-" + btnid).addClass('hidden');
    }

    function hidebutton(obj) {
        var linkid = obj.id;
        var btnid = linkid.replace("idAttachRow-", "");
        $("#idAttachBtn-" + btnid).addClass('hidden');
        $("#idAttachSpace-" + btnid).removeClass('hidden');
    }
    
</script>

app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calendar</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <environment names="Staging,Development">
                    <a asp-area="" asp-controller="Events" asp-action="Index" class="navbar-brand">Calendar (Non-Prod)</a>
                </environment>

                <environment names="Production">
                    <a asp-area="" asp-controller="Events" asp-action="Index" class="navbar-brand">Calendar</a>
                </environment>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Events" asp-action="Index">Events</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Calendar</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>