app/Models/Attachment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Calendar.Models
{
    public class Attachment
    {
        public int ID { get; set; }
        [Required]
        public int EventID { get; set; }
        [StringLength(255), Required]
        public string FileName { get; set; }
        [StringLength(500), Required]
        public string FilePath { get; set; }

        [Display(Name = "Creation Date"), DisplayFormat(DataFormatString = "{0:MMM d, yyyy h:mm tt}", ApplyFormatInEditMode = false), DataType(DataType.DateTime)]
        public DateTime CreatedDate { get; set; }
        [Display(Name = "Created By"), StringLength(50)]
        public string CreatedBy { get; set; }
        [Display(Name = "Created By"), StringLength(50)]
        public string CreatedByDisplayName { get; set; }
        [Display(Name = "Last Updated"), DisplayFormat(DataFormatString = "{0:MMM d, yyyy h:mm tt}", ApplyFormatInEditMode = false), DataType(DataType.DateTime)]
        public DateTime UpdatedDate { get; set; }
        [Display(Name = "Updated By"), StringLength(50)]
        public string UpdatedBy { get; set; }
        [Display(Name = "Updated By"), StringLength(50)]
        public string UpdatedByDisplayName { get; set; }
    }
}

app/Controllers/AttachmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Calendar.Data;
using Calendar.Models;
using Calendar.Helpers;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting.Server;
using System.Net;

namespace Calendar.Controllers
{
    public class AttachmentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;
        public Attachment tempAttachment;

        public IEnumerable<Attachment> ListAll()
        {
            return _context.Attachment.AsEnumerable();
        }

        //public AttachmentsController(ApplicationDbContext context)
        //{
        //    _context = context;
        //}

        public AttachmentsController(ApplicationDbContext context, IHostingEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        public async Task<IActionResult> Index(int? eventid)
        {
            //var attachment = await _context.Attachment.SingleOrDefaultAsync(m => m.EventID == eventid);
            if (eventid == null)
            {
                return View(await _context.Attachment.OrderBy(m => m.EventID).ThenBy(m => m.ID).ToListAsync());
            }
            else
            {
                return View(await _context.Attachment.Where(m => m.EventID == eventid).OrderBy(m => m.EventID).ThenBy(m => m.ID).ToListAsync());
            }
        }

        // GET: Attachments 
        public async Task<IActionResult> IndexPartial(int eventid)
        {
            return PartialView("AttachPartial", await _context.Attachment.Where(m => m.EventID == eventid).ToListAsync());
        }


        // GET: Attachments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var attachment = await _context.Attachment.SingleOrDefaultAsync(m => m.ID == id);
            if (attachment == null)
            {
                return NotFound();
            }

            return View(attachment);
        }

        // GET: Attachments/Create
        public IActionResult Create()
        {
            if (!User.IsInRole(Constants.ROLE_ADMIN))
                return NotFound();

            return View();
        }

        // POST: Attachments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,EventID,FileName,FilePath")] Attachment attachment)
        {

            if (!User.IsInRole(Constants.ROLE_ADMIN))
                return NotFound();

            if (ModelState.IsValid)
            {
                /* Audit Fields */
                var username = "anonymous";
                var u = User.Claims.Where(m => m.Type == "username");
                if (u.Count() == 1) { username = u.First().Value; }
                var displayname = "anonymous";
                var d = User.Claims.Where(m => m.Type == "displayName");
                if (d.Count() == 1) { displayname = d.First().Value; }
                attachment.CreatedDate = DateTime.Now;
                attachment.CreatedBy = username;
                attachment.CreatedByDisplayName = displayname;
                attachment.UpdatedDate = attachment.CreatedDate;
                attachment.UpdatedBy = username;
                attachment.UpdatedByDisplayName = displayname;

                _context.Add(attachment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(attachment);
        }

        // GET: Attachments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!User.IsInRole(Constants.ROLE_ADMIN))
                return NotFound();

            if (id == null)
            {
                return NotFound();
            }

            var attachment = await _context.Attachment.SingleOrDefaultAsync(m => m.ID == id);
            if (attachment == null)
            {
                return NotFound();
            }
            return View(attachment);
        }

        // POST: Attachments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,EventID,FileName,FilePath,CreatedDate,CreatedBy,CreatedByDisplayName")] Attachment attachment)
        {
            if (!User.IsInRole(Constants.ROLE_ADMIN))
                return NotFound();

            if (id != attachment.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    /* Audit Fields */
                    var username = "anonymous";
                    var u = User.Claims.Where(m => m.Type == "username");
                    if (u.Count() == 1) { username = u.First().Value; }
                    var displayname = "anonymous";
                    var d = User.Claims.Where(m => m.Type == "displayName");
                    if (d.Count() == 1) { displayname = d.First().Value; }
                    attachment.UpdatedDate = DateTime.Now;
                    attachment.UpdatedBy = username;
                    attachment.UpdatedByDisplayName = displayname;

                    _context.Update(attachment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AttachmentExists(attachment.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { eventid = attachment.EventID });
            }
            return View(attachment);
        }

        // GET: Attachments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!User.IsInRole(Constants.ROLE_ADMIN))
                return NotFound();

            if (id == null)
            {
                return NotFound();
            }

            var attachment = await _context.Attachment.SingleOrDefaultAsync(m => m.ID == id);
            if (attachment == null)
            {
                return NotFound();
            }

            return View(attachment);
        }

        // POST: Attachments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, string ajax)
        {
            if (!User.IsInRole(Constants.ROLE_ADMIN))
                return NotFound();

            var attachment = await _context.Attachment.SingleOrDefaultAsync(m => m.ID == id);
            var uploaddir = Path.Combine(_environment.WebRootPath, "uploads", attachment.EventID.ToString(), attachment.ID.ToString());
            string fullPath = Path.Combine(uploaddir, attachment.FileName);
            try
            {
                if (System.IO.File.Exists(fullPath))
                {
                    //delete the file
                    System.IO.File.Delete(fullPath);

                    //delete the directory for file
                    System.IO.Directory.Delete(uploaddir);
                }
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }
            _context.Attachment.Remove(attachment);
            await _context.SaveChangesAsync();

            if (ajax == "true")
                return new EmptyResult();
            else
                return RedirectToAction("Index");
        }

        private bool AttachmentExists(int id)
        {
            return _context.Attachment.Any(e => e.ID == id);
        }

        [HttpPost]
        public async Task<JsonResult> AjaxUpload(ICollection<IFormFile> AttachFile, int EventID, string redir = null, string ajax = null)
        {
            try
            {
                var uploaddir = Path.Combine(_environment.WebRootPath, "uploads", EventID.ToString());
                var attachment = new Attachment();
                tempAttachment = attachment;

                if (AttachFile != null) { 
                    foreach (var file in AttachFile)
                    {
                        if (file.Length > 0)
                        {
                            /* Audit Fields */
                            var username = "anonymous";
                            var u = User.Claims.Where(m => m.Type == "username");
                            if (u.Count() == 1) { username = u.First().Value; }
                            var displayname = "anonymous";
                            var d = User.Claims.Where(m => m.Type == "displayName");
                            if (d.Count() == 1) { displayname = d.First().Value; }
                            attachment.CreatedDate = DateTime.Now;
                            attachment.CreatedBy = username;
                            attachment.CreatedByDisplayName = displayname;
                            attachment.UpdatedDate = attachment.CreatedDate;
                            attachment.UpdatedBy = username;
                            attachment.UpdatedByDisplayName = displayname;

app/Views/Attachments/Create.cshtml
@model Calendar.Models.Attachment

@inject Calendar.Controllers.AppSettingsController appsettings

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form>
<!--<form asp-action="Create">-->
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label id="attachment" class="col-md-2 control-label" data-toggle="tooltip" data-placement="top" title="File">File</label>
            <div class="col-md-10">
                <input type="file" class="file" id="idFile" name="AttachFile" multiple>
                <div id="kv-error-2" class="alert alert-danger fade in" style="margin-top:10px;display:none"></div>
            </div>
        </div>
        <!--<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>-->
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script type="text/javascript" src="~/lib/jquery/dist/jquery.js">
    $(document).ready(function () {

        $("#idFile").fileinput({
            theme: "explorer",
            uploadUrl: '@Url.Action("Upload2", "Attachments")', // server upload action
            uploadAsync: true,
            dropZoneEnabled: false, // disable drag and drop file function
            maxFileCount: 5,
            overwriteInitial: false,
            //elErrorContainer: 'kv-error-1',
            previewFileIcon: '<i class="fa fa-file"></i>',
            initialPreviewAsData: true, // defaults markup
            fileActionSettings: {
                removeTitle: 'Remove file from list',
                showZoom: false
            },
            layoutTemplates: {
                preview: '<div class="file-preview {class}">\n' +
                '    <div class="{dropClass}">\n' +
                '    <table class="table table-bordered table-hover"><tbody class="file-preview-thumbnails">\n' +
                '    </tbody></table>\n' +
                '    <div class="clearfix"></div>' +
                '    <div class="file-preview-status text-center text-success"></div>\n' +
                '    <div class="kv-fileinput-error"></div>\n' +
                '    </div>\n' +
                '</div>'
            },
            uploadExtraData: function (previewId, index) {
                var obj = {};
                if (previewId == undefined) {
                    return obj;
                } else {
                    obj = { EventID: "1085", redir: "null" };
                }
                return obj;
            },
            allowedFileExtensions: ["jpg", "png", "gif", "pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "txt", "log", "zip", "7z"],
            preferIconicPreview: true, // this will force thumbnails to display icons for following file extensions
            previewFileIconSettings: { // configure your icon file extensions
                'doc': '<i class="fa fa-file-word-o text-primary"></i>',
                'xls': '<i class="fa fa-file-excel-o text-success"></i>',
                'ppt': '<i class="fa fa-file-powerpoint-o text-danger"></i>',
                'pdf': '<i class="fa fa-file-pdf-o text-danger"></i>',
                'zip': '<i class="fa fa-file-archive-o text-muted"></i>',
                'htm': '<i class="fa fa-file-code-o text-info"></i>',
                'txt': '<i class="fa fa-file-text-o text-info"></i>',
                'mov': '<i class="fa fa-file-movie-o text-warning"></i>',
                'mp3': '<i class="fa fa-file-audio-o text-warning"></i>',
                // note for these file types below no extension determination logic
                // has been configured (the keys itself will be used as extensions)
                'jpg': '<i class="fa fa-file-photo-o text-danger"></i>',
                'gif': '<i class="fa fa-file-photo-o text-muted"></i>',
                'png': '<i class="fa fa-file-photo-o text-primary"></i>'
            },
            previewFileExtSettings: { // configure the logic for determining icon file extensions
                'doc': function (ext) {
                    return ext.match(/(doc|docx)$/i);
                },
                'xls': function (ext) {
                    return ext.match(/(xls|xlsx)$/i);
                },
                'ppt': function (ext) {
                    return ext.match(/(ppt|pptx)$/i);
                },
                'zip': function (ext) {
                    return ext.match(/(zip|rar|tar|gzip|gz|7z)$/i);
                },
                'htm': function (ext) {
                    return ext.match(/(htm|html)$/i);
                },
                'txt': function (ext) {
                    return ext.match(/(txt|ini|csv|java|php|js|css)$/i);
                },
                'mov': function (ext) {
                    return ext.match(/(avi|mpg|mkv|mov|mp4|3gp|webm|wmv)$/i);
                },
                'mp3': function (ext) {
                    return ext.match(/(mp3|wav)$/i);
                },
            }
        });

    });

</script>

app/Views/Attachments/Delete.cshtml
@model Calendar.Models.Attachment

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EventID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EventID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>
        <dd>
            ~\uploads\@Html.DisplayFor(model => model.EventID)\@Html.DisplayFor(model => model.ID)\@Html.DisplayFor(model => model.FileName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedByDisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedByDisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

app/Views/Attachments/Details.cshtml
@model Calendar.Models.Attachment

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EventID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EventID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FilePath)
        </dt>
        <dd>
            ~\uploads\@Html.DisplayFor(model => model.EventID)\@Html.DisplayFor(model => model.ID)\@Html.DisplayFor(model => model.FileName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedByDisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedByDisplayName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Delete" asp-route-id="@Model.ID">Delete</a> |
    <a asp-action="Index">Back to List</a>
</div>

app/Views/Attachments/Edit.cshtml
@model Calendar.Models.Attachment

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>
<h2>@ViewData["Title"] - ID @Html.DisplayFor(model => model.ID), <span id="idStatusInTitle"></span></h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Attachment</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="FileName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FileName" class="form-control" />
                <span asp-validation-for="FileName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FilePath" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FilePath" class="form-control" />
                <span asp-validation-for="FilePath" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="EventID" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="EventID" class="form-control" readonly />
                <span asp-validation-for="EventID" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

app/Views/Attachments/Index.cshtml
@model IEnumerable<Calendar.Models.Attachment>

@{
    ViewData["Title"] = "Index";
}

<h2>Attachment</h2>


<div class="tab-pane active" id="2a">
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.EventID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FileName)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.EventID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        <a href="/uploads/@Html.DisplayFor(modelItem => item.EventID)/@Html.DisplayFor(modelItem => item.ID)/@Html.DisplayFor(modelItem => item.FileName)" target="_blank">@Html.DisplayFor(modelItem => item.FileName)</a>
                    </td>
                    <td>
                        <!--<a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |-->
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

app/Views/Attachments/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calendar</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput-typeahead.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.css" />  
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/css/fileinput.min.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/themes/explorer/theme.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/themes/fa/theme.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/css/font-awesome.min.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/css/calendar-common.css" />
        <link rel="stylesheet" href="~/css/event.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput-typeahead.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/css/fileinput.min.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/themes/explorer/theme.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/themes/fa/theme.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/css/font-awesome.min.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/css/calendar-common.min.css" />
        <link rel="stylesheet" href="~/css/event.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment names="Development">
        <script src="~/lib/tether/dist/js/tether.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/moment/min/moment-with-locales.min.js"></script>
        <script src="~/lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
        <script src="~/lib/typeahead.js/dist/typeahead.bundle.js"></script>
        <script src="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.js"></script>
        <script src="~/lib/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js" type="text/javascript"></script>
        <script src="~/lib/bootstrap-fileinput/js/fileinput.js"></script>
        <script src="~/lib/bootstrap-fileinput/themes/explorer/theme.js"></script>
        <script src="~/lib/bootstrap-fileinput/themes/fa/theme.js"></script>
        <script src="~/js/event.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/tether/dist/js/tether.min.js"
                asp-fallback-src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.1/js/tether.min.js">
        </script>
        <script src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/lib/moment/min/moment-with-locales.min.js"></script>
        <script src="~/lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
        <script src="~/lib/typeahead.js/dist/typeahead.bundle.min.js"></script>
        <script src="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js"></script>
        <script src="~/lib/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js" type="text/javascript"></script>
        <script src="~/lib/bootstrap-fileinput/js/fileinput.js"></script>
        <script src="~/lib/bootstrap-fileinput/themes/explorer/theme.js"></script>
        <script src="~/lib/bootstrap-fileinput/themes/fa/theme.js"></script>
        <script src="~/lib/bootstrap-fileinput/themes/explorer/fa.js"></script>
        <script src="~/js/event.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        /* IE only. Prompt message when Compatibility Mode is turned on.*/
        var ie = IeVersion();

        if (ie.CompatibilityMode)
            alert("This Calendar does't support Compatibility Mode. Please turn it off and retry.");
    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <environment names="Staging,Development">
                    <a asp-area="" asp-controller="Events" asp-action="Index" class="navbar-brand">Calendar (Non-Prod)</a>
                </environment>

                <environment names="Production">
                    <a asp-area="" asp-controller="Events" asp-action="Index" class="navbar-brand">Calendar</a>
                </environment>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Events" asp-action="Index">Events</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @if (!User.IsInRole(Calendar.Helpers.Constants.ROLE_ADMIN))
        {
            <br />
            <div class="alert alert-danger">
                <span>Access denied.</span>
            </div>
            IgnoreBody();
        }
        else
        {
            @RenderBody()
        }
        <hr />
        <footer>
            <p>&copy; 2016 - Calendar</p>
        </footer>
    </div>

</body>
</html>