app/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Calendar.Models
{
    public class Event : IValidatableObject
    {
        public int ID { get; set; }
        [Display(Name = "Start Time"), DisplayFormat(DataFormatString = "{0:MMM d, yyyy h:mm tt}", ApplyFormatInEditMode = true), DataType(DataType.DateTime), Required]
        public DateTime StartDateTime { get; set; }
        [Display(Name = "End Time"), DisplayFormat(DataFormatString = "{0:MMM d, yyyy h:mm tt}", ApplyFormatInEditMode = true), DataType(DataType.DateTime), Required]
        public DateTime EndDateTime { get; set; }
        [StringLength(500, MinimumLength = 3), Required]
        public string Subject { get; set; }
        [Display(Name = "Short Description"), StringLength(500, MinimumLength = 3), Required]
        public string TaskDescription { get; set; }
        [StringLength(50, MinimumLength = 3), Required]
        public string Category { get; set; }
        [Display(Name = "Hosts"), StringLength(500, MinimumLength = 3), Required]
        public string AffectedHosts { get; set; }
        [Display(Name = "Projects"), StringLength(300, MinimumLength = 2), Required]
        public string AffectedProjects { get; set; }
        [Display(Name = "Risk Level"), StringLength(10), Required]
        public string RiskLevel { get; set; }
        [Display(Name = "Teams"), StringLength(150, MinimumLength = 2), Required]
        public string AffectedTeams { get; set; }
        [Display(Name = "Reference"), StringLength(50)]
        public string Reference { get; set; }
        [Display(Name = "Results"), StringLength(100, MinimumLength = 3)]
        public string Result { get; set; }

        [Display(Name = "Environment"), StringLength(10), Required]
        public string Environment { get; set; }
        [Display(Name = "Action By"), StringLength(100)]
        public string ActionBy { get; set; }
        [Display(Name = "Health Check By"), StringLength(100)]
        public string HealthCheckBy { get; set; }
        [Display(Name = "Failure Likelihood"), StringLength(10), Required]
        public string Likelihood { get; set; }
        [Display(Name = "Failure Impact"), StringLength(10), Required]
        public string Impact { get; set; }

        [Display(Name = "Status"), StringLength(5)]
        public string EventStatus { get; set; }        
        [Display(Name = "Service Impact"), StringLength(1000), DataType(DataType.MultilineText)]
        public string ImpactAnalysis { get; set; }
        [Display(Name = "Action Plan"), StringLength(1000)]
        public string MaintProcedure { get; set; }
        [Display(Name = "Verification Steps"), StringLength(1000)]
        public string VerificationStep { get; set; }
        [Display(Name = "Fallback Procedure"), StringLength(1000)]
        public string FallbackProcedure { get; set; }

        [Display(Name = "Creation Date"), DisplayFormat(DataFormatString = "{0:MMM d, yyyy h:mm tt}", ApplyFormatInEditMode = false), DataType(DataType.DateTime)]
        public DateTime CreatedDate { get; set; }
        [Display(Name = "Created By"), StringLength(50)]
        public string CreatedBy { get; set; }
        [Display(Name = "Created By"), StringLength(50)]
        public string CreatedByDisplayName { get; set; }
        [Display(Name = "Last Updated"), DisplayFormat(DataFormatString = "{0:MMM d, yyyy h:mm tt}", ApplyFormatInEditMode = false), DataType(DataType.DateTime)]
        public DateTime UpdatedDate { get; set; }
        [Display(Name = "Updated By"), StringLength(50)]
        public string UpdatedBy { get; set; }
        [Display(Name = "Updated By"), StringLength(50)]
        public string UpdatedByDisplayName { get; set; }

        [Display(Name = "Risk Analysis"), StringLength(1000), DataType(DataType.MultilineText)]
        public string RiskAnalysis { get; set; }

        /* The Severity is to be obsolete. Once commented, EF will drop the column when execute "dotnet ef database update" */
        //[Display(Name = "Severity")]
        //public int Severity { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (StartDateTime > EndDateTime)
                yield return new ValidationResult("Start Time cannot be later than End Time.", new[] { "StartDateTime", "EndDateTime" });
            if (StartDateTime == EndDateTime)
                yield return new ValidationResult("Start Time and End Time cannot be the same.", new[] { "StartDateTime", "EndDateTime" });
        }
        /* navigation properties */
        public ICollection<Acknowledgement> Acknowledgements { get; set; }
    }
}

app/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Calendar.Data;
using Calendar.Models;
using Calendar.Models.CalendarViewModels;
using Calendar.Helpers;

namespace Calendar.Controllers
{
    public class EventsController : Controller
    {
        const int DAYSINAWEEK = 7;
        private readonly ApplicationDbContext _context;


        public EventsController(ApplicationDbContext context)
        {
            _context = context;    
        }


        // GET: Events
        //startdate_desc, startdate_asce, creation_desc, creation_asce
        public async Task<IActionResult> Index(string sort, string eventid, string subject, string searchrange, string searchday, string host, string project, string team, string refid, string searchdatefrom, string searchdateto, int? page, int? pgsize)
        {
            ViewBag.SortParm = String.IsNullOrEmpty(sort) ? "" : sort;
            ViewBag.SubjectParm = String.IsNullOrEmpty(subject) ? "" : subject;
            ViewBag.HostParm = String.IsNullOrEmpty(host) ? "" : host;
            ViewBag.ProjParm = String.IsNullOrEmpty(project) ? "" : project;
            ViewBag.TeamParm = String.IsNullOrEmpty(team) ? "" : team;
            ViewBag.RefParm = String.IsNullOrEmpty(refid) ? "" : refid;
            ViewBag.RangeParm = searchrange;
            ViewBag.DayParm = searchday;
            ViewBag.EventParm = String.IsNullOrEmpty(eventid) ? "" : eventid;
            ViewBag.FromParm = String.IsNullOrEmpty(searchdatefrom) ? "" : searchdatefrom;
            ViewBag.ToParm = String.IsNullOrEmpty(searchdateto) ? "" : searchdateto;
            
            if (String.IsNullOrEmpty(eventid) && String.IsNullOrEmpty(subject) 
                && String.IsNullOrEmpty(host) && String.IsNullOrEmpty(project) 
                && String.IsNullOrEmpty(team) && String.IsNullOrEmpty(refid) 
                && (String.IsNullOrEmpty(searchday) || searchday.Equals("ND")))
            {
                ViewBag.SearchOn = "";
            } else
            {
                ViewBag.SearchOn = "in";
            }

            var events = from e in _context.Event
                           select e;

            int n_eventid;          
            if (!String.IsNullOrEmpty(eventid) && Int32.TryParse(eventid, out n_eventid))
            {
                events = events.Where(e => e.ID.Equals(n_eventid));
            }

            if (!String.IsNullOrEmpty(subject))
            {
                events = events.Where(e => e.Subject.Contains(subject));
            }
            if (!String.IsNullOrEmpty(host))
            {
                events = events.Where(e => e.AffectedHosts.Contains(host));
            }
            if (!String.IsNullOrEmpty(project))
            {
                events = events.Where(e => e.AffectedProjects.Contains(project));
            }
            if (!String.IsNullOrEmpty(team))
            {
                events = events.Where(e => e.AffectedTeams.Contains(team));
            }
            if (!String.IsNullOrEmpty(refid))
            {
                events = events.Where(e => e.Reference.Contains(refid));
            }

            DateTime datetimefrom;
            DateTime datetimeto;

            if (!String.IsNullOrEmpty(searchdatefrom) || !String.IsNullOrEmpty(searchdateto))
            {

                if (searchday.Equals("SD"))
                {
                    if (!String.IsNullOrEmpty(searchdatefrom) && DateTime.TryParse(searchdatefrom, out datetimefrom))
                    {
                        events = events.Where(e => e.StartDateTime >= datetimefrom);
                    }
                    if (!String.IsNullOrEmpty(searchdateto) && DateTime.TryParse(searchdateto, out datetimeto))
                    {
                        events = events.Where(e => e.EndDateTime <= datetimeto);
                    }
                }
                else if(searchday.Equals("CD"))
                {
                    if (!String.IsNullOrEmpty(searchdatefrom) && DateTime.TryParse(searchdatefrom, out datetimefrom))
                    {
                        events = events.Where(e => e.CreatedDate >= datetimefrom);
                    }
                    if (!String.IsNullOrEmpty(searchdateto) && DateTime.TryParse(searchdateto, out datetimeto))
                    {
                        events = events.Where(e => e.CreatedDate <= datetimeto);
                    }
                }
                else
                {
                    if (!String.IsNullOrEmpty(searchdatefrom) && DateTime.TryParse(searchdatefrom, out datetimefrom))
                    {
                        events = events.Where(e => e.UpdatedDate >= datetimefrom);
                    }
                    if (!String.IsNullOrEmpty(searchdateto) && DateTime.TryParse(searchdateto, out datetimeto))
                    {
                        events = events.Where(e => e.UpdatedDate <= datetimeto);
                    }
                }
            }
            else
            {                
                switch (searchrange)
                {
                    case "S1":
                        events = events.Where(e => e.StartDateTime.Date >= DateTime.Now.Date && e.StartDateTime.Date <= (DateTime.Now.AddDays(1).Date));
                        break;
                    case "S2":
                        events = events.Where(e => e.StartDateTime.Date >= DateTime.Now.Date && e.StartDateTime.Date <= (DateTime.Now.AddDays(7).Date));
                        break;
                    case "S3":
                        events = events.Where(e => e.StartDateTime.Date >= DateTime.Now.Date && e.StartDateTime.Date <= (DateTime.Now.AddDays(30).Date));
                        break;
                    case "S4":
                        events = events.Where(e => e.StartDateTime.Date >= DateTime.Now.Date && e.StartDateTime.Date <= (DateTime.Now.AddDays(90).Date));
                        break;
                    case "C1":
                        events = events.Where(e => e.CreatedDate.Date >= DateTime.Now.Date && e.CreatedDate.Date <= (DateTime.Now.AddDays(1).Date));
                        break;
                    case "C2":
                        events = events.Where(e => e.CreatedDate.Date >= (DateTime.Now.AddDays(-7).Date) && e.CreatedDate.Date <= DateTime.Now.Date);
                        break;
                    case "C3":
                        events = events.Where(e => e.CreatedDate.Date >= (DateTime.Now.AddDays(-30).Date) && e.CreatedDate.Date <= DateTime.Now.Date);
                        break;
                    case "C4":
                        events = events.Where(e => e.CreatedDate.Date >= (DateTime.Now.AddDays(-90).Date) && e.CreatedDate.Date <= DateTime.Now.Date);
                        break;
                    case "U1":
                        events = events.Where(e => e.UpdatedDate.Date >= DateTime.Now.Date && e.UpdatedDate.Date <= (DateTime.Now.AddDays(1).Date));
                        break;
                    case "U2":
                        events = events.Where(e => e.UpdatedDate.Date >= (DateTime.Now.AddDays(-7).Date) && e.UpdatedDate.Date <= DateTime.Now.Date);
                        break;
                    case "U3":
                        events = events.Where(e => e.UpdatedDate.Date >= (DateTime.Now.AddDays(-30).Date) && e.UpdatedDate.Date <= DateTime.Now.Date);
                        break;
                    case "U4":
                        events = events.Where(e => e.UpdatedDate.Date >= (DateTime.Now.AddDays(-90).Date) && e.UpdatedDate.Date <= DateTime.Now.Date);
                        break;
                    default:
                        break;
                }
            }

            switch (sort)
            {
                case "cd_a":
                    events = events.OrderBy(e => e.CreatedDate);
                    break;
                case "cd_d":
                    events = events.OrderByDescending(e => e.CreatedDate);
                    break;
                case "ud_a":
                    events = events.OrderBy(e => e.UpdatedDate);
                    break;
                case "ud_d":
                    events = events.OrderByDescending(e => e.UpdatedDate);
                    break;
                case "sd_a":
                    events = events.OrderBy(e => e.StartDateTime);
                    break;
                default:   // sd_d
                    events = events.OrderByDescending(e => e.StartDateTime);
                    break;
            }
            
            var viewModel = new EventIndexData();
            viewModel.Events = events
                  .Include(e => e.Acknowledgements)
                  .AsNoTracking();
            
            return View(new PaginatedEventIndex(viewModel, page ?? 1, pgsize ?? 30));

            //return View(await PaginatedList<Event>.CreateAsync(events.AsNoTracking(), page ?? 1, pgsize ?? 30));

            //return View(await events.AsNoTracking().ToListAsync());
            //return View(await _context.Event.OrderByDescending(m => m.StartDateTime).ToListAsync());
        }


        // GET: Events/Calendar
        public async Task<IActionResult> Calendar(int? year, int? month, int? reviewEventId, int? reviewDirection, string filterProject, string filterTeam)
        {
            DateTime now = System.DateTime.Now;
            DateTime ViewDate;

            if (year == null)
            {
                year = now.Year;
                month = now.Month;
            } else if (month == null)
            {
                month = now.Month;                
            }

            try
            {
                ViewDate = new DateTime((int)year, (int)month, 1);
            }
            catch (ArgumentOutOfRangeException)

app/Views/Events/Delete.cshtml
@model Calendar.Models.Event

@{
    ViewData["Title"] = "Delete Event";
}

<h2>@ViewData["Title"]</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaskDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaskDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AffectedHosts)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AffectedHosts)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AffectedProjects)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AffectedProjects)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AffectedTeams)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AffectedTeams)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Reference)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Reference)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Result)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Result)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="hidden" name="Redir" value="@ViewBag.Redir" />
            <input type="submit" value="Confirm Delete" class="btn btn-default" /> |
            @if (@ViewBag.Redir != null)
            {
                <a href="@Uri.UnescapeDataString(ViewBag.Redir)">Back</a>
            }
            else
            {
                <a asp-action="Index">Back</a>
            }
        </div>
    </form>
</div>

app/Views/Events/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calendar</title>

    <environment names="Development">        
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput-typeahead.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.css" />  
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/css/fileinput.min.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/themes/explorer/theme.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/themes/fa/theme.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/css/font-awesome.min.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/css/calendar-common.css" />
        <link rel="stylesheet" href="~/css/event.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput-typeahead.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/css/fileinput.min.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/themes/explorer/theme.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/lib/bootstrap-fileinput/themes/fa/theme.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/css/font-awesome.min.css" media="all" type="text/css" />
        <link rel="stylesheet" href="~/css/calendar-common.min.css" />
        <link rel="stylesheet" href="~/css/event.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment names="Development">
        <script src="~/lib/tether/dist/js/tether.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/moment/min/moment-with-locales.min.js"></script>
        <script src="~/lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>        
        <script src="~/lib/typeahead.js/dist/typeahead.bundle.js"></script>
        <script src="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.js"></script>
        <script src="~/lib/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js" type="text/javascript"></script>
        <script src="~/lib/bootstrap-fileinput/js/fileinput.js"></script>
        <script src="~/lib/bootstrap-fileinput/themes/explorer/theme.js"></script>
        <script src="~/lib/bootstrap-fileinput/themes/fa/theme.js"></script>
        <script src="~/js/event.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/tether/dist/js/tether.min.js"
                asp-fallback-src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.1/js/tether.min.js">
        </script>
        <script src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>        
        <script src="~/lib/moment/min/moment-with-locales.min.js"></script>
        <script src="~/lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
        <script src="~/lib/typeahead.js/dist/typeahead.bundle.min.js"></script>
        <script src="~/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js"></script>
        <script src="~/lib/bootstrap-fileinput/js/plugins/canvas-to-blob.min.js" type="text/javascript"></script>
        <script src="~/lib/bootstrap-fileinput/js/fileinput.js"></script>
        <script src="~/lib/bootstrap-fileinput/themes/explorer/theme.js"></script>
        <script src="~/lib/bootstrap-fileinput/themes/fa/theme.js"></script>
        <script src="~/lib/bootstrap-fileinput/themes/explorer/fa.js"></script>
        <script src="~/js/event.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        /* IE only. Prompt message when Compatibility Mode is turned on.*/
        var ie = IeVersion();

        if (ie.CompatibilityMode)
            alert("This Calendar does't support Compatibility Mode. Please turn it off and retry.");
    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <environment names="Staging,Development">
                    <a asp-area="" asp-controller="Events" asp-action="Index" class="navbar-brand">Calendar (Non-Prod)</a>
                </environment>

                <environment names="Production">
                    <a asp-area="" asp-controller="Events" asp-action="Index" class="navbar-brand">Calendar</a>
                </environment>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Events" asp-action="Index">List</a></li>
                    <li><a asp-area="" asp-controller="Events" asp-action="Calendar">Month</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")                
            </div>
        </div>
    </div>
    <div class="container body-content" id="idContainer">
        @RenderBody()
        <hr hidden />
        <footer>
            <p hidden>&copy; 2016 - Calendar</p>
        </footer>
    </div>   
</body>
</html>

app/Views/Events/_LayoutCalendar.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calendar</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css" />
        <link rel="stylesheet" href="~/css/calendar-common.css" />
        <link rel="stylesheet" href="~/css/calendar.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />
        <link rel="stylesheet" href="~/css/calendar-common.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/calendar.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/tether/dist/js/tether.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/bootstrap-treeview/public/js/bootstrap-treeview.js"></script>
        <script src="~/lib/moment/min/moment-with-locales.min.js"></script>
        <script src="~/lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
        <script src="~/js/calendar.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="~/lib/tether/dist/js/tether.min.js"
                asp-fallback-src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.1/js/tether.min.js">
        </script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/lib/bootstrap-treeview/dist/bootstrap-treeview.min.js"></script>
        <script src="~/lib/moment/min/moment-with-locales.min.js"></script>
        <script src="~/lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
        <script src="~/js/calendar.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        /* IE only. Prompt message when Compatibility Mode is turned on.*/
        var ie = IeVersion();

        if (ie.CompatibilityMode)
            alert("This Calendar does't support Compatibility Mode. Please turn it off and retry.");
    </script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <environment names="Staging,Development">
                    <a asp-area="" asp-controller="Events" asp-action="Index" class="navbar-brand">Calendar (Non-Prod)</a>
                </environment>

                <environment names="Production">
                    <a asp-area="" asp-controller="Events" asp-action="Index" class="navbar-brand">Calendar</a>
                </environment>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Events" asp-action="Index">List</a></li>
                    <li><a asp-area="" asp-controller="Events" asp-action="Calendar">Month</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>